### ISSUE TITLE
Getting Error: Unable to resolve action. Repository not found: jetpack-io/devbox-install-action When trying to use  jetify-com/devbox-install-action

### ISSUE THREAD

**Issue by msdolbey** [jetify-com/devbox-install-action#43]
I've used both
jetify-com/devbox-install-action@v0.8.0
and 
jetify-com/devbox-install-action@v0.9.0

in our github action workflow yaml, and both are failing to retrieve the repo, and instead I'm seeing this return:

```
Error: Unable to resolve action. Repository not found: jetpack-io/devbox-install-action
```

**Comment by Lagoja** [comment]
Hey @msdolbey, thanks for reporting. Investigating now

**Comment by Lagoja** [comment]
Hey @msdolbey, I can't reproduce this on our own repos. Is it possible the action is used in multiple places, or do you have some sort of caching in place for actions?

If you're ok sharing the full workflow yaml, I could also debug with the team some more

**Comment by alim-banked** [comment]
I also just ran into same issue as well
```
Getting action download info
Error: Unable to resolve action. Repository not found: jetpack-io/devbox-install-action
```

```
uses: jetpack-io/devbox-install-action@v0.7.0
      with:
        project-path: ${{ steps.symlink.outputs.action_path }}
        enable-cache: 'true'
        refresh-cli: 'false'
        disable-nix-access-token: 'false'
        devbox-version: 0.7.0
```

**Comment by alim-banked** [comment]
https://github.com/jetify-com/devbox-install-action/pull/42
seems like maybe because of this ^ change?

**Comment by savil** [comment]
A couple of clarifications: it seems we had to re-publish the releases (since Github didn't auto-migrate over the old github action). IIUC `0.9.0` was re-published. 

The snippet below seems to be working for us (in our internal repos):
```
      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.9.0
        with:
          enable-cache: true
```

Could you share the yaml snippet that you have tried with that is failing?

**Comment by alim-banked** [comment]
Is 0.7.0 republished? This is what I have
```
uses: jetpack-io/devbox-install-action@v0.7.0
      with:
        enable-cache: 'true'
        refresh-cli: 'false'
        disable-nix-access-token: 'false'
        devbox-version: 0.7.0
```
