### ISSUE TITLE
Action fails with error 127 when `init_hook` is present in devbox.json

### ISSUE THREAD

**Issue by kpervin** [jetify-com/devbox-install-action#60]
Using the following files:

```json
{
  "$schema": "https://raw.githubusercontent.com/jetify-com/devbox/0.13.6/.schema/devbox.schema.json",
  "packages": {
    "azure-cli":  "2.64.0",
    "terraform":  "1.9.8",
    "ansible":    "2.17.5",
    "packer":     "1.11.2",
    "git":        "2.46.1"
  },
  "shell": {
    "init_hook": [
      "echo 'Welcome to devbox!'",
      "[[ -f \".env.bash\" ]] && . .env.bash"
    ],
    "scripts": {
      "test": [
        "echo \"Error: no test specified\" && exit 1"
      ]
    }
  }
}
```

```yaml
name: 'Cache Devbox'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'devbox.json'
      - 'devbox.lock'

jobs:
  cache-devbox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.11.0
        with:
          enable-cache: 'true'
        env:
          DEVBOX_DEBUG: 1
```

![image](https://github.com/user-attachments/assets/7eefa577-a762-4a4a-97b9-d7fb05492552)

Let me know if there is anything else I need to provide to help debug this.
